--- #
--- # Create Namespace for each team/student
---
apiVersion: v1
kind: Namespace
metadata:
  name: red
---
--- # ConfigMap for team namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: red-collector-config
  namespace: red
data:
  COLLECTOR_CONFIG: 'http://red-student-ui'
  INSTRUCTOR_CONFIG: 'http://dashboard.default'
--- # 
--- # Create Deployment for each team/student  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-student-ui
  namespace: red
  labels:
    app: red-student-ui
spec:
  selector:
    matchLabels:
      app: red-student-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: red-student-ui
    spec:
      containers:
      - name: red-student-ui
        image: ibmicpcoc/collector:V3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: COLLECTOR_CONFIG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
--- #
--- # Create Servie for each team/student
---
apiVersion: v1
kind: Service
metadata:
  name: red-student-ui
  namespace: red
  labels:
    app: red-student-ui
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31001
      targetPort: 3000
      protocol: TCP
      name: red-student-ui
  selector:
    app: red-student-ui

