---
--- # Create ClusterImagePolicy to allow pulling images from a specific docker repository.  
---
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: {{repoName}}
spec:
  repositories:
  - name: docker.io/{{repoName}}/*
    policy:
      va:
        enabled: false
