--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-eagle
  namespace: red
  labels:
    app: red-eagle
spec:
  selector:
    matchLabels:
      app: red-eagle
  replicas: 1
  template:
    metadata:
      labels:
        app: red-eagle
    spec:
      containers:
      - name: red-eagle
        image: ibmicpcoc/eagle:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4100
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
---
--- # Service defs
---
apiVersion: v1
kind: Service
metadata:
  name: red-eagle
  namespace: red
  labels:
    app: red-eagle
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4100
      protocol: TCP
      name: red-eagle
  selector:
    app: red-eagle
