--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: blue-pv 
  labels:
    user: blue
spec:
  capacity:
    storage: 1Mi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /storage/blue/pvc001
    server: 169.62.225.199
  persistentVolumeReclaimPolicy: Recycle    

--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-offer
  namespace: blue
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      user: blue
--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-offer
  namespace: blue
  labels:
    app: blue-offer
spec:
  selector:
    matchLabels:
      app: blue-offer
  replicas: 1
  template:
    metadata:
      labels:
        app: blue-offer
    spec:
      containers:
      - name: blue-offer
        image: ibmicpcoc/offer:latest
        imagePullPolicy: Always
        command: ["node", "app.js"]
        volumeMounts:
        - name: offer-data
          mountPath: /data
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: blue-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: blue-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
      volumes:
      - name: offer-data
        persistentVolumeClaim:
          claimName: blue-offer