--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab  17 
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: red-panda
  namespace: red
  labels:
    app: red-panda
spec:
  selector:
    matchLabels:
      app: red-panda
  replicas: 1
  serviceName: red-panda-server
  template:
    metadata:
      labels:
        app: red-panda
    spec:
      containers:
      - name: red-panda
        image: ibmicpcoc/offer:latest
        imagePullPolicy: Always
        command: ["node", "app.js"]
        volumeMounts:
        - name: red-panda-data
          mountPath: /data
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always            
  volumeClaimTemplates:
  - metadata:
      name: red-panda-data
      namespace: red
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Mi
      storageClassName: managed-nfs-storage 
