---
--- # Service defs
---
apiVersion: v1
kind: Service
metadata:
  name: red-quake
  namespace: red
  labels:
    app: red-quake
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4400
      protocol: TCP
      name: red-quake
  selector:
    app: red-quake
--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-quake
  namespace: red
  labels:
    app: red-quake
spec:
  selector:
    matchLabels:
      app: red-quake
  replicas: 1
  template:
    metadata:
      labels:
        app: red-quake
    spec:
      containers:
      - name: red-quake
        image: ibmicpcoc/quake:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 4100
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: INSTRUCTOR_CONFIG
          - name: ROUTE
            value: "hotdog-red.gfstst.169.62.225.197.nip.io"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi

  
  
  
  
  
  
  
  
  
  
  
  