kind: Pod
apiVersion: v1
metadata:
  labels:
    zone: us-east-coast
    cluster: downward-api-test-cluster1
    rack: rack-123
  name: dapi-volume-test-pod
  annotations:
    annotation1: "345"
    annotation2: "456"
spec:
  containers:
  - name: volume-test-container
    image: gcr.io/google_containers/busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: podinfo
      mountPath: /tmp/etc
      readOnly: false
    env:
    - name: APP_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APP_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: COLLECTOR_CONFIG
      valueFrom: 
        configMapKeyRef:
          name: red-collector-config
          key: COLLECTOR_CONFIG
    - name: INSTRUCTOR_CONFIG
      valueFrom: 
        configMapKeyRef:
          name: red-collector-config
          key: INSTRUCTOR_CONFIG
    resources:
      requests:
        cpu: 50m
        memory: 50Mi

  volumes:
  - name: podinfo
    downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          fieldPath: metadata.name
        path: pod_name
      - fieldRef:
          fieldPath: metadata.namespace
        path: pod_namespace
      - fieldRef:
          fieldPath: metadata.labels
        path: pod_labels
      - fieldRef:
          fieldPath: metadata.annotations
        path: pod_annotations


  restartPolicy: Always            
