apiVersion: v1
kind: Pod
metadata:
  namespace: red
  name: red-dns
spec:
  containers:
    - name: red-dns
      image: busybox:1.28
      command:
      - sleep
      - "3600"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.2.3.4
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0