apiVersion: v1
kind: Pod
metadata:
  namespace: red
  name: red-tools
spec:
  containers:
    - name: red-tools
      image: ibmicpcoc/nettools:latest
      command:
      - sleep
      - "3600"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.2.3.4
      - 8.8.8.8
