apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-limited
spec:
  containers:
    - name: dns-limited
      image: ibmicpcoc/nettools:latest
      command:
      - sleep
      - "3600"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.2.3.4
      - 8.8.8.8  
      - 10.186.171.86
    searches:
      - default.svc.cluster.local 
      - svc.cluster.local 
      - cluster.local 
