apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-claim
  namespace: red
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      user: red
