--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-igloo
  namespace: red
  labels:
    app: red-igloo
spec:
  selector:
    matchLabels:
      app: red-igloo
  replicas: 1
  template:
    metadata:
      labels:
        app: red-igloo
    spec:
      containers:
      - name: red-igloo
        image: ibmicpcoc/igloo:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: red-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
            
        readinessProbe:
          httpGet:
            path: /ready
            port: 4100
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        livenessProbe:
          httpGet:
            path: /health
            port: 4100
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10    
---
--- # Service defs
---
apiVersion: v1
kind: Service
metadata:
  name: red-igloo
  namespace: red
  labels:
    app: red-igloo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4100
      protocol: TCP
      name: red-igloo
  selector:
    app: red-igloo